#:schema node_modules/wrangler/config-schema.json
name = "grab-times-car"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date="2024-10-22"

[triggers]
# 00:00 JST for every day
crons = ["00 15 * * *"]

[observability]
enabled = true

[vars]
API_URL = "https://apps.plus.timescar.jp/tcpappsweb/tcpServlet"
